### PR TITLE
Added retired site of weex

### PR DESCRIPTION
**Pull request by WillemJiang**
As sebb suggested we can just add a directory entry for the retirement. 

https://lists.apache.org/thread.html/re412c99987badb24c9d50976211346b3775aa42a19900b442f920e75%40%3Cgeneral.incubator.apache.org%3E

### CODE REVIEW

**Comment by bdelacretaz** [comment]
I think we need a traceable explanation of why this is being created, as the purpose is not obvious at all from looking at those files.

I suggest that you create a ticket at https://issues.apache.org/jira/projects/INCUBATOR which explains why this is needed, and the INCUBATOR-nnnn ID of that ticket can the be included in comments of the index.html file for clarity.

**Comment by WillemJiang** [comment]
Please check out https://issues.apache.org/jira/browse/INCUBATOR-266 for more information.

**Comment by sebbASF** [comment]
Looks good to me.

**Comment by bdelacretaz** [comment]
I see that a README has been added to https://github.com/apache/incubator/tree/master/assets/retired to explain these redirects, thank you for this! It helps explain what's happening, and resolves my concern about traceability.

**Pull request merged**
